home/urls.py
from django.urls import path

from . import views

app_name = "home" 

urlpatterns = [
    path('', views.home, name='myhome'),
    path('home/', views.home, name='myhome'),
    path('about/', views.about, name='myabout'),
    path('experiences/', views.experience, name='myexperience'),
    path('portfolio/', views.portfolio, name='myportfolio'),
    path('contact/', views.contact, name='mycontact'),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls'))
    
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/HomeStory2.html')

def about(request):
    return render(request, 'home/AboutMeStory2.html')

def experience(request):
    return render(request, 'home/ExperiencesStory2.html')

def portfolio(request):
    return render(request, 'home/PortfolioStory2.html')

def contact(request):
    return render(request, 'home/ContactStory2.html')

home/templates/home/AboutMeStory2.html
{% extends "home/base.html" %}
{% load static %}

{% block page_content %}
    <p id="about-me">ABOUT ME</p>
    
    <div class="container-about">
        <div class ="education">
            <p id="my-education">Education</p>
            <img src="{% static 'img/about-wave-2.png' %}" class="wave-about-2">
            <div class="education">
                <div class="education-line"></div>
                <div class="edu-content">
                    <p class="edu-date" id="date1">2018 - Now</p>
                    <p class="edu-name" id="name1">University of Indonesia <br>Information System Student</p>
                </div>
                <div class="edu-content">
                    <p class="edu-date" id="date2">2015 - 2018</p>
                    <p class="edu-name" id="name2">Fons Vitae 1 Senior High School</p>
                </div>
            </div>
        </div>
   
        <div class="skills">
            <p id="my-skills">My Skills</p>
            <div class="skills-stamps">
                <div class="skill-content">
                    <img src="{% static 'img/python-stamp.png' %}">
                    <p>Python</p>
                </div>
                <div class="skill-content">
                    <img src="{% static 'img/Java-stamp.png' %}">
                    <p>Java</p>
                </div>
                <div class="skill-content">
                    <img src="{% static 'img/html-stamp.png' %}">
                    <p>HTML</p>
                </div>
                <div class="skill-content">
                    <img src="{% static 'img/css-stamp.png' %}">
                    <p>CSS</p>
                </div>
            </div>
        </div>
        <div class="about-center-line"></div>
        <div class="postcard-text">
                <p>Hello! I’m Michelle!<br>
                I’m interested in design and technology, especially<br>
                at web development and I’m ready to send this<br>
                postcard all over the world! See you soon! :D 
                </p> 
        </div>
            
        <div class="postcard-line">
            <hr>
            <hr>
            <hr>
            <hr>
        </div>
    </div>
    
    <img src="{% static 'img/photo-stamp.png' %}" class="photo-stamp">
    <img src="{% static 'img/wave-about-1.png' %}" class="wave-about-1">
    <p class="text-background zindex-dropdown" id="about"> ABOUT </p>
{% endblock %}
   

home/templates/home/ContactStory2.html
{% extends "home/base.html" %}
{% load static %}

{% block page_content %}
    <div class="contact-text">
        <img src="{% static 'img/line-wave.png' %}" id="left-wave">
        <p id="get-in-touch">LET’S GET IN TOUCH WITH ME!</p>
        <p id="michelle-melissa">Michelle Melissa</p>
        <img src="{% static 'img/line-wave.png' %}" id="right-wave">
    </div>

    <div class="contact-icon">
        <div><a href="https://www.linkedin.com/in/michelle-melissa" target="_blank"><img src="{% static 'img/linkedin.png' %}"></a></div>
        <div><a href="https://www.instagram.com/chelmel.18/" target="_blank"><img src="{% static 'img/instagram.png' %}"></a></div>
        <div><a href="mailto:melissa.chelle18@gmail.com" target="_blank"><img src="{% static 'img/email (1).png' %}"></a></div>
        <div><a href="https://gitlab.com/chelmel18" target="_blank"><img src="{% static 'img/gitlab.png' %}"></a></div>
    </div>
    <p class="text-background" id="contact"> CONTACT </p>
{% endblock %}
    

home/templates/home/ExperiencesStory2.html
{% extends "home/base.html" %}
{% load static %}

{% block page_content %}
    <p id="my-experiences">MY EXPERIENCES</p>
    <div class="list-exp">
        <ul class="list-unstyled">
        <li class="media">
          <img src="{% static 'img/profpic.jpg' %}" class="mr-3" alt="Pemira IKM Fasilkom UI Logo">
          <div class="media-body">
            <h5 class="mt-0 mb-1">September 2019 - Present</h5>
            <p class="exp-content">General Secretary of Pemira IKM Fasilkom UI 2019</p>
          </div>
        </li>
        
        <li class="media">
          <img src="{% static 'img/logo-bem-text.png' %}" class="mr-3" alt="BEM Fasilkom UI Logo">
          <div class="media-body">
            <h5 class="mt-0 mb-1">February 2019 - Present</h5>
            <p class="exp-content">Staff of Media Bureau at BEM Fasilkom UI 2019</p>
        </div>
        </li>

        <li class="media my-4">
            <img src="{% static 'img/logo-wisgen.png' %}" class="mr-3" alt="Even Graduation Ceremony of Fasilkom UI 2019 Logo">
            <div class="media-body">
              <h5 class="mt-0 mb-1">July - August 2019</h5>
              <p class="exp-content">Staff of Decoration at Even Graduation Ceremony of Fasilkom UI 2019</p>
            </div>
        </li>

        <li class="media my-4">
            <img src="{% static 'img/logo-compfest.jpg' %}" class="mr-3" alt="Compfest XI Logo">
            <div class="media-body">
                <h5 class="mt-0 mb-1">February - September 2019</h5>
                <p class="exp-content">Staff of Food and Beverages at Compfest XI</p>
            </div>
          </li>
        
        <li class="media my-4">
            <img src="{% static 'img/logo-cgt.jpg' %}" class="mr-3" alt="CGT in Action Logo">
            <div class="media-body">
                <h5 class="mt-0 mb-1">February - May 2019</h5>
                <p class="exp-content">Staff of Fundraising at 26th CGT in Action</p>
            </div>
          </li>
        
        <li class="media my-4">
            <img src="{% static 'img/logo-bkui.jpg' %}" class="mr-3" alt="BKUI 2018 Logo">
            <div class="media-body">
                <h5 class="mt-0 mb-1">September - November 2019</h5>
                <p class="exp-content">Volunteer of Finance at Bedah Kampus UI 2018</p>
            </div>
          </li>
        
      </ul>
    </div>
    <!--
    
    <div class="experiences">
        <div class="vertical-line"></div>
        <div class="left-container">
            <div class="content">
                <h1 class="date"> AKU KIRI </h1>
                <p class="experience-name"> General Secretary of Pemira IKM Fasilkom UI 2019 </p>
            </div>
        </div>
        <div class="right-container">
                <h1 class="date"> KAMU KANAN </h1>
                <p class="experience-name"> General Secretary of Pemira IKM Fasilkom UI 2019 </p>
        </div>
    </div>
    -->
    <p class="text-background" id="experience"> EXPER</p>
{% endblock %}
    

home/templates/home/HomeStory2.html
{% extends "home/base.html" %}

{% load static %}
{% block page_content %}
    <img src="{% static 'img/photo2-01.jpg' %}" id="profile-photo">
    <img src="{% static 'img/line-wave.png' %}" id="wave-profile">
    <h1 class="hello-text">Hello I’m Michelle!<br>Welcome to my page!</h1>
    <p class="text-background" id="hello"> HELLO </p>
{% endblock %}

home/templates/home/PortfolioStory2.html
{% extends "home/base.html" %}
{% load static %}

{% block page_content %}

    <p id="my-portfolio">PORTFOLIO</p>
    <div class="portfolio-card">
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/nyepi.png' %}" class="card-img-top" alt="Nyepi Card">
          <div class="card-body">
            <h5 class="card-title">Bali Day of Silence Card</h5>
            <p class="card-text">I designed a Bali Day of Silence greeting card for BEM Fasilkom UI</p>
          </div>
        </div>
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/idul-adha.png' %}" class="card-img-top" alt="Idul Adha Card">
          <div class="card-body">
            <h5 class="card-title">Eid al Adha Card</h5>
            <p class="card-text">I designed an Eid al Adha greeting card for BEM Fasilkom UI</p>
          </div>
        </div>
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/jumat-agung.png' %}" class="card-img-top" alt="Jumat Agung Card">
          <div class="card-body">
            <h5 class="card-title">Good Friday Card</h5>
            <p class="card-text">I designed a Good Friday greeting card for BEM Fasilkom UI</p>
          </div>
      </div>
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/waisak.png' %}" class="card-img-top" alt="Waisak Card">
          <div class="card-body">
            <h5 class="card-title">Vesak Card</h5>
            <p class="card-text">I designed a Vesak greeting card for BEM Fasilkom UI</p>
          </div>
      </div>
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/banner-ilkom.png' %}" class="card-img-top" alt="Banner Ilmu Komputer">
          <div class="card-body">
            <h5 class="card-title">Computer Science Banner for Bedah Kampus UI 2019</h5>
            <p class="card-text">I designed a Computer Science Banner for Bedah Kampus UI 2019</p>
          </div>
      </div>
      <div class="card" style="width: 18rem;">
        <img src="{% static 'img/banner-si.png' %}" class="card-img-top" alt="Banner Sistem Informasi">
        <div class="card-body">
          <h5 class="card-title">Information System Banner for Bedah Kampus UI 2019</h5>
          <p class="card-text">I designed an Information System Banner for Bedah Kampus UI 2019</p>
        </div>
      </div>
    <div class="card" style="width: 18rem;">
      <img src="{% static 'img/id-card.png' %}" class="card-img-top" alt="ID Card Design">
      <div class="card-body">
        <h5 class="card-title">ID Card of Even Graduation Ceremony of Fasilkom UI</h5>
        <p class="card-text">I designed an ID Card for Even Graduation Ceremony of Fasilkom UI 2019</p>
      </div>
    </div>
    </div>
   
  <p class="text-background" id="portfolio"> PORTFOLIO </p>
{% endblock %}
    

home/templates/home/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/CSSStory2.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Michelle Melissa</title>
    </head>
<body>
    <header>
        <div class ="header-border">
            <br>
        </div>
        <div class="logo">
            <a href="{% url 'home:myhome' %}"><img src="{% static 'img/logo-web-01.png' %}"></a>
        </div>
        <nav> 
            <ul>
                <li><a href="{% url 'home:myhome' %}">Home</a></li>
                <li><a href="{% url 'home:myabout' %}">About Me</a></li>
                <li><a href="{% url 'home:myexperience' %}">Experiences</a></li>
                <li><a href="{% url 'home:myportfolio' %}">Portfolio</a></li>
                <li><a href="{% url 'home:mycontact' %}">Contact</a></li>
            </ul>
        </nav>
    </header>
    {% block page_content %}
    {% endblock %}
    
    <footer>
        <div class ="footer-border" id="home-border">
            <br>
        </div>
    </footer>
</body>
</html>